---
# This workflow integrates ShiftLeft with GitHub
# Visit https://docs.shiftleft.io for help
name: Qwiet AI

on:
  push:
    branches:
     - master
     - main
  pull_request:
  workflow_dispatch:

jobs:
  NextGen-Static-Analysis:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Download ShiftLeft cli
      run: |
        curl https://cdn.shiftleft.io/download/sl > ${GITHUB_WORKSPACE}/sl && chmod a+rx ${GITHUB_WORKSPACE}/sl
    - name: Extract branch name
      shell: bash
      run: echo "branch=${GITHUB_REF#refs/heads/}" >> $GITHUB_OUTPUT
      id: extract_branch
    - uses: AppThreat/cpggen-action@main
      with:
        out_dir: "/github/workspace/cpg_out"
    - name: Analyze
      run: |
        #####
        # Run Qwiet analysis
        if [ -e "/github/workspace/cpg_out" ]; then
          for i in `ls /github/workspace/cpg_out/*.manifest.json`; do
            cpg=$(jq -r ".cpg" $i)
            sbom=$(jq -r ".sbom" $i)
            language=$(jq -r ".language" $i)
            ${GITHUB_WORKSPACE}/sl analyze --tag app.group=$(basename $(pwd)) --app $(basename $(pwd))-$language --$language --cpgupload $cpg --bomupload $sbom
          done
        else
          echo "CPG was not generated successfully"
        fi
        #####
      env:
        SHIFTLEFT_ACCESS_TOKEN: ${{ secrets.SHIFTLEFT_ACCESS_TOKEN }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SL_CPG_OPTS: "-J-Xms2g -J-Xmx7g"
        SHIFTLEFT_JAVA_OPTS: "-Xms2g -Xmx7g"
    - name: Upload cpg
      uses: actions/upload-artifact@v1.0.0
      with:
        name: cpg
        path: cpg_out
